// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/95b7178e0ef33b4b88327676418b4cc3ad61df0f/moment/moment.d.ts
declare var moment: moment.MomentStatic;